--OSOBA insert
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(1,1,1);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(2,2,2);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(3,3,3);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(4,3,4);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(5,2,5);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(6,2,6);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(7,1,7);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(8,3,8);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(9,2,9);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(10,1,10);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(11,3,11);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(12,1,12);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(13,2,13);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(14,1,14);
INSERT INTO Oddzial(ID_ODDZIALU, Zmiana, ID_JEDNOSTKI) VALUES(15,1,15);
