INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(1,'Strażak');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(2,'Woźny');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(3,'Dyrektor');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(4,'Menadzer');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(5,'Technik');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(6,'Kierowca');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(7,'Sekretarka');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(8,'Księgowa');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(9,'Dyżurny');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(10,'Strażak');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(11,'Kierownik');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(12,'Zastępca kierownika');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(13,'Ochroniarz');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(14,'Specjalista');
INSERT INTO Stanowisko(ID_STANOWISKA,Nazwa) VALUES(15,'Zastępca kierownika');