

CREATE TABLE Kontakt
(
	ID_KONTAKTU NUMERIC NOT NULL PRIMARY KEY,
	Numer_telefonu VARCHAR2(12) NOT NULL,
	Mail VARCHAR2(25)
);


CREATE TABLE Adres
(
	ID_ADRESU NUMERIC NOT NULL PRIMARY KEY,
	Ulica VARCHAR2(20) NOT NULL,
	Miasto VARCHAR2(20) NOT NULL,
	Kod_pocztowy VARCHAR2(7) NOT NULL
);

CREATE TABLE Firma
(
	ID_FIRMY NUMERIC NOT NULL PRIMARY KEY,
	Nazwa VARCHAR2(20) NOT NULL,
	ID_KONTAKTU NUMERIC NOT NULL,
	ID_ADRESU NUMERIC NOT NULL, 

	CONSTRAINT fk_FirmaKontakt FOREIGN KEY(ID_KONTAKTU) REFERENCES Kontakt(ID_KONTAKTU),
	CONSTRAINT fk_FirmaAdres FOREIGN KEY(ID_ADRESU) REFERENCES Adres(ID_ADRESU)
);

CREATE TABLE Ubezpieczenie
(
	ID_UBEZPIECZENIA NUMERIC NOT NULL PRIMARY KEY,
	Rodzaj VARCHAR2(20) NOT NULL,
	Data_konca VARCHAR2(20) NOT NULL, 
	ID_FIRMY NUMERIC NOT NULL,

	CONSTRAINT fk_UbezpieczenieFirma FOREIGN KEY(ID_FIRMY) REFERENCES Firma(ID_FIRMY)
);

CREATE TABLE Osoba
(
	ID_OSOBY NUMERIC NOT NULL PRIMARY KEY,
	Imie VARCHAR2(20) NOT NULL, 
	Nazwisko VARCHAR2(20) NOT NULL,
	Pesel VARCHAR2(11) NOT NULL UNIQUE,
	ID_KONTAKTU NUMERIC NOT NULL,
	ID_ADRESU NUMERIC NOT NULL,
	ID_UBEZPIECZENIA NUMERIC NOT NULL,

	CONSTRAINT fk_OsobaKontakt FOREIGN KEY(ID_KONTAKTU) REFERENCES Kontakt(ID_KONTAKTU),
	CONSTRAINT fk_OsobaAdres FOREIGN KEY(ID_ADRESU) REFERENCES Adres(ID_ADRESU),
	CONSTRAINT fk_OsobaUbezpieczenie FOREIGN KEY(ID_UBEZPIECZENIA) REFERENCES Ubezpieczenie(ID_UBEZPIECZENIA)
);

CREATE TABLE Stanowisko
(
	ID_STANOWISKA NUMERIC NOT NULL PRIMARY KEY,
	Nazwa VARCHAR2(20) NOT NULL
);

CREATE TABLE Jednostka
(
	ID_JEDNOSTKI NUMERIC NOT NULL PRIMARY KEY,
	Nazwa VARCHAR2(20) NOT NULL,
	ID_KONTAKTU NUMERIC NOT NULL,
	ID_ADRESU NUMERIC NOT NULL,

	CONSTRAINT fk_JednostkaKontakt FOREIGN KEY(ID_KONTAKTU) REFERENCES Kontakt(ID_KONTAKTU),
	CONSTRAINT fk_JednostkaAdres FOREIGN KEY(ID_ADRESU) REFERENCES Adres(ID_ADRESU)
);

CREATE TABLE Oddzial
(
	ID_ODDZIALU NUMERIC NOT NULL PRIMARY KEY,
	Zmiana NUMERIC NOT NULL CHECK(Zmiana IN (1,2,3)),
	ID_JEDNOSTKI NUMERIC NOT NULL,

	CONSTRAINT fk_OddzialJednostka FOREIGN KEY (ID_JEDNOSTKI) REFERENCES Jednostka(ID_JEDNOSTKI)
);

CREATE TABLE Strazak
(
	ID_STRAZAKA NUMERIC NOT NULL PRIMARY KEY,
	Wynagrodzenie VARCHAR2(20) NOT NULL,
	Telefon_sluzbowy VARCHAR2(12),
	Data_zatrudnienia VARCHAR2(12) NOT NULL,
	ID_STANOWISKA NUMERIC NOT NULL,
	ID_OSOBY NUMERIC NOT NULL,
	ID_ODDZIALU NUMERIC NOT NULL,

	CONSTRAINT fk_StrazakStanowisko FOREIGN KEY(ID_STANOWISKA) REFERENCES Stanowisko(ID_STANOWISKA),
	CONSTRAINT fk_StrazakOsoba FOREIGN KEY(ID_OSOBY) REFERENCES Osoba(ID_OSOBY),
	CONSTRAINT fk_StrazakOddzial FOREIGN KEY(ID_ODDZIALU) REFERENCES Oddzial(ID_ODDZIALU)
);

CREATE TABLE Pojazd
(
	ID_POJAZDU NUMERIC NOT NULL PRIMARY KEY,
	Rodzaj VARCHAR2(20) NOT NULL,
	Numer_Rejestracyjny VARCHAR2(20) NOT NULL UNIQUE,
	ID_UBEZPIECZENIA NUMERIC NOT NULL,

	CONSTRAINT fk_PojazdUbezpiezczenie FOREIGN KEY(ID_UBEZPIECZENIA) REFERENCES Ubezpieczenie(ID_UBEZPIECZENIA)
);

CREATE TABLE Sprzet
(
	ID_SPRZETU NUMERIC NOT NULL PRIMARY KEY,
	Nazwa VARCHAR2(20) NOT NULL
);

CREATE TABLE Zgloszenie
(
	ID_ZGLOSZENIA NUMERIC NOT NULL PRIMARY KEY,
	Data_zgloszenia VARCHAR2(20) NOT NULL,
	Opis VARCHAR2(50) NOT NULL,
	ID_ADRESU NUMERIC NOT NULL,
	ID_ODDZIALU NUMERIC NOT NULL,
	ID_POJAZDU NUMERIC NOT NULL,
	ID_SPRZETU NUMERIC NOT NULL,

	CONSTRAINT fk_ZgloszenieAdres FOREIGN KEY(ID_ADRESU) REFERENCES Adres(ID_ADRESU),
	CONSTRAINT fk_ZgloszenieOddzial FOREIGN KEY(ID_ODDZIALU) REFERENCES Oddzial(ID_ODDZIALU),
	CONSTRAINT fk_ZgloszeniePojazd FOREIGN KEY(ID_POJAZDU) REFERENCES Pojazd(ID_POJAZDU),
	CONSTRAINT fk_ZgloszenieSprzet FOREIGN KEY(ID_SPRZETU) REFERENCES Sprzet(ID_SPRZETU)
);