--JEDNOSTKA insert
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(1,'OSP A',1,1);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(2,'OSP B',2,2);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(3,'OSP C',3,3);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(4,'OSP D',4,4);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(5,'OSP E',5,5);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(6,'OSP F',6,6);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(7,'OSP H',7,7);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(8,'OSP I',8,8);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(9,'OSP J',9,9);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(10,'OSP K',10,10);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(11,'OSP L',11,11);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(12,'OSP M',12,12);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(13,'OSP N',13,13);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(14,'OSP O',14,14);
INSERT INTO Jednostka(ID_JEDNOSTKI, Nazwa, ID_KONTAKTU, ID_ADRESU) VALUES(15,'OSP P',15,15);